---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-servvice
  labels:
    author: Vamsi
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    author: Vamsi
    name: voting-app
...