---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    author: Vamsi
    name: voting-app
spec:
  containers:
    - name: voting-app
      images: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...